# Yazi keymap configuration
# Optimized for lightweight usage with integration to fzf, ripgrep, and bat

[mgr]
prepend_keymap = [
  # FZF integration
  { on = "<C-f>", run = "shell --block 'fd --type f --hidden --follow | fzf --height 40% --reverse | xargs -I {} echo \"reveal {}\"' --confirm", desc = "Find files with fzf" },
  { on = "<C-g>", run = "shell --block 'rg --files-with-matches \"\" | fzf --height 40% --reverse | xargs -I {} echo \"reveal {}\"' --confirm", desc = "Find files with content using ripgrep" },
  
  # Quick navigation
  { on = "gh", run = "cd ~", desc = "Go to home directory" },
  { on = "gc", run = "cd ~/.config", desc = "Go to config directory" },
  { on = "gd", run = "cd ~/dotfiles", desc = "Go to dotfiles directory" },
  { on = "gp", run = "cd ~/adhoc-projects", desc = "Go to projects directory" },
  { on = "gr", run = "cd /", desc = "Go to root directory" },
  
  # File operations
  { on = "Y", run = "copy path", desc = "Copy file path" },
  { on = "P", run = "paste --force", desc = "Paste with force" },
  { on = "x", run = "cut", desc = "Cut file" },
  { on = "d", run = "remove", desc = "Delete file" },
  { on = "D", run = "remove --permanently", desc = "Delete permanently" },
  
  # View operations
  { on = "i", run = "peek", desc = "Peek file content" },
  { on = "I", run = "shell --block 'bat --style=numbers --color=always \"$0\"' --confirm", desc = "View file with bat" },
  { on = "<C-p>", run = "arrow -1", desc = "Move up" },
  { on = "<C-n>", run = "arrow 1", desc = "Move down" },
  
  # Bookmarks
  { on = "m", run = "shell --block 'echo \"bookmark set $(pwd)\" | sh' --confirm", desc = "Set bookmark" },
  { on = "'", run = "shell --block 'echo \"bookmark go\" | sh' --confirm", desc = "Go to bookmark" },
  
  # Search
  { on = "/", run = "find", desc = "Find in current directory" },
  { on = "?", run = "find --previous", desc = "Find previous" },
  { on = "n", run = "find_arrow", desc = "Next search result" },
  { on = "N", run = "find_arrow --previous", desc = "Previous search result" },
  
  # Selection
  { on = "<Space>", run = "select --state=none", desc = "Toggle selection" },
  { on = "v", run = "visual_mode", desc = "Enter visual mode" },
  { on = "V", run = "visual_mode --unset", desc = "Exit visual mode" },
  { on = "A", run = "select_all --state=true", desc = "Select all" },
  { on = "a", run = "select_all --state=none", desc = "Invert selection" },
  
  # Sorting
  { on = "S", run = "sort modified --dir_first", desc = "Sort by modified time" },
  { on = "s", run = "sort alphabetical --dir_first", desc = "Sort alphabetically" },
  { on = "z", run = "sort size --dir_first", desc = "Sort by size" },
  
  # Hidden files
  { on = ".", run = "hidden toggle", desc = "Toggle hidden files" },
  
  # Archive operations
  { on = "ae", run = "shell --block 'aunpack \"$0\"' --confirm", desc = "Extract archive" },
  { on = "ac", run = "shell --block 'apack \"$0.tar.gz\" \"$0\"' --confirm", desc = "Create archive" },
  
  # Git operations
  { on = "gg", run = "shell --block 'git status' --confirm", desc = "Git status" },
  { on = "gl", run = "shell --block 'git log --oneline -10' --confirm", desc = "Git log" },
  { on = "gd", run = "shell --block 'git diff' --confirm", desc = "Git diff" },
  
  # File info
  { on = "f", run = "filter", desc = "Filter files" },
  { on = "F", run = "filter --smart", desc = "Smart filter" },
  { on = "o", run = "open", desc = "Open file" },
  { on = "O", run = "open --interactive", desc = "Open with..." },
  
  # Tabs
  { on = "t", run = "tab_create --current", desc = "Create new tab" },
  { on = "T", run = "tab_close", desc = "Close tab" },
  { on = "1", run = "tab_switch 0", desc = "Switch to tab 1" },
  { on = "2", run = "tab_switch 1", desc = "Switch to tab 2" },
  { on = "3", run = "tab_switch 2", desc = "Switch to tab 3" },
  { on = "4", run = "tab_switch 3", desc = "Switch to tab 4" },
  { on = "5", run = "tab_switch 4", desc = "Switch to tab 5" },
  { on = "[", run = "tab_switch -1 --relative", desc = "Previous tab" },
  { on = "]", run = "tab_switch 1 --relative", desc = "Next tab" },
  
  # Tasks
  { on = "w", run = "tasks_show", desc = "Show tasks" },
  
  # Help
  { on = "~", run = "help", desc = "Show help" },
  
  # Quit
  { on = "q", run = "quit", desc = "Quit" },
  { on = "Q", run = "quit --no-cwd-file", desc = "Quit without saving cwd" },
  
  # Refresh
  { on = "R", run = "refresh", desc = "Refresh" },
  { on = "<C-r>", run = "refresh", desc = "Refresh" },
  
  # Create new
  { on = "c", run = "create", desc = "Create new file/directory" },
  { on = "r", run = "rename", desc = "Rename file" },
  
  # Image viewing
  { on = "p", run = "preview", desc = "Preview image" },
  { on = "P", run = "preview --close", desc = "Close preview" },
]

[tasks]
keymap = [
  { on = "<Esc>", run = "close", desc = "Close task manager" },
  { on = "q", run = "close", desc = "Close task manager" },
  { on = "k", run = "arrow -1", desc = "Move up" },
  { on = "j", run = "arrow 1", desc = "Move down" },
  { on = "<C-k>", run = "arrow -1", desc = "Move up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move down" },
  { on = "<Enter>", run = "inspect", desc = "Inspect task" },
  { on = "c", run = "cancel", desc = "Cancel task" },
  { on = "r", run = "refresh", desc = "Refresh tasks" },
]

[select]
keymap = [
  { on = "<Esc>", run = "close", desc = "Close select" },
  { on = "q", run = "close", desc = "Close select" },
  { on = "k", run = "arrow -1", desc = "Move up" },
  { on = "j", run = "arrow 1", desc = "Move down" },
  { on = "<C-k>", run = "arrow -1", desc = "Move up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move down" },
  { on = "<Enter>", run = "close --submit", desc = "Submit selection" },
]

[input]
keymap = [
  { on = "<Esc>", run = "close", desc = "Close input" },
  { on = "<C-c>", run = "close", desc = "Close input" },
  { on = "<Enter>", run = "close --submit", desc = "Submit input" },
  { on = "<C-h>", run = "backspace", desc = "Backspace" },
  { on = "<Backspace>", run = "backspace", desc = "Backspace" },
  { on = "<C-d>", run = "delete", desc = "Delete" },
  { on = "<Delete>", run = "delete", desc = "Delete" },
  { on = "<C-a>", run = "move -999", desc = "Move to start" },
  { on = "<Home>", run = "move -999", desc = "Move to start" },
  { on = "<C-e>", run = "move 999", desc = "Move to end" },
  { on = "<End>", run = "move 999", desc = "Move to end" },
  { on = "<C-f>", run = "move 1", desc = "Move forward" },
  { on = "<Right>", run = "move 1", desc = "Move forward" },
  { on = "<C-b>", run = "move -1", desc = "Move backward" },
  { on = "<Left>", run = "move -1", desc = "Move backward" },
  { on = "<C-w>", run = "backward_kill_word", desc = "Kill word backward" },
  { on = "<C-u>", run = "kill_line", desc = "Kill line" },
  { on = "<C-k>", run = "kill_line_after", desc = "Kill line after cursor" },
  { on = "<C-y>", run = "yank", desc = "Yank" },
]

[completion]
keymap = [
  { on = "<Esc>", run = "close", desc = "Close completion" },
  { on = "<C-c>", run = "close", desc = "Close completion" },
  { on = "<Tab>", run = "close --submit", desc = "Submit completion" },
  { on = "<Enter>", run = "close --submit", desc = "Submit completion" },
  { on = "<C-k>", run = "arrow -1", desc = "Move up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move down" },
  { on = "<Up>", run = "arrow -1", desc = "Move up" },
  { on = "<Down>", run = "arrow 1", desc = "Move down" },
]

[help]
keymap = [
  { on = "<Esc>", run = "close", desc = "Close help" },
  { on = "q", run = "close", desc = "Close help" },
  { on = "k", run = "arrow -1", desc = "Move up" },
  { on = "j", run = "arrow 1", desc = "Move down" },
  { on = "<C-k>", run = "arrow -1", desc = "Move up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move down" },
  { on = "<Up>", run = "arrow -1", desc = "Move up" },
  { on = "<Down>", run = "arrow 1", desc = "Move down" },
] 
